kind: Deployment
apiVersion: apps/v1
metadata:
  name: ubuntu-wget
  namespace: aquatest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-wget
  template:
    metadata:
      labels:
        app: ubuntu-wget
        deployment: ubuntu-wget
    spec:
      containers:
        - name: ubuntu-wget
          image: stanhoe/ubuntu-wget:latest
          command:
            - /bin/sleep
            - 3650d
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
